CREATE TABLE articles(
	id SERIAL PRIMARY KEY,
	title TEXT,
	content TEXT,
	username TEXT NOT NULL REFERENCES users(username) ON UPDATE CASCADE ON DELETE CASCADE,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);